apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: robandpdx-admin-ops-rd-large
  namespace: actions-runner-system
spec:
  template:
    spec:
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      organization: robandpdx-admin-ops
      githubAPICredentialsFrom:
        secretRef:
          name: arc-robandpdx-admin-ops
      group: large
      labels:
        - large
      resources:
        limits:
          cpu: "1.0"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "1Gi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: robandpdx-admin-ops-rd-autoscaler-large
  namespace: actions-runner-system
spec:
  githubAPICredentialsFrom:
    secretRef:
      name: arc-robandpdx-admin-ops
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: robandpdx-admin-ops-rd-large
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'