# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: example-runner
  namespace: actions-runner-system
spec:
  organization: robandpdx-admin-ops
  githubAPICredentialsFrom:
        secretRef:
          name: arc-robandpdx-admin-ops