apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: robandpdx-volcano-runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      organization: robandpdx-volcano
      githubAPICredentialsFrom:
        secretRef:
          name: arc-robandpdx-volcano
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: robandpdx-volcano-runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  githubAPICredentialsFrom:
    secretRef:
      name: arc-robandpdx-volcano
  # Runners in the targeted RunnerDeployment won't be scaled down
  # for 5 minutes instead of the default 10 minutes now
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: robandpdx-volcano-runner-deployment
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'